### ISSUE TITLE
The script doesn't load the ttktheme

### ISSUE THREAD

**Issue by Nekuake** [Nekuake/Internet-Speed-Monitor#6]

**Comment by github9751** [comment]
It's too slow to start on windows→Internet-Speed-Monitor-GUI
cpu i5 4590/8G
Best regards

**Comment by Nekuake** [comment]
Please, open a new issue for that. I am working on it, though

**Comment by Nekuake** [comment]
This issue doesn't make any sense since Dark theme is not being used at the moment. Issue closed for now.
